### ISSUE TITLE
Name collisions

### ISSUE THREAD

**Issue by trilogysci** [Frege/frege-native-gen#6]
While running on a large set of classes I can across a number of name issues and generation issues.

* it does not check if the class is an abstract class and will still generate new method
* it does not detect if there are static methods with the same name as instance methods and generates code with the same name for both which fails. The following code is based on the Rect class in android (see http://developer.android.com/reference/android/graphics/Rect.html) the first is the static and the second is the instance method.

        native intersects android.graphics.Rect.intersects :: Mutable s Rect -> Mutable s Rect -> ST s Bool
        native intersects :: Mutable s Rect -> Int -> Int -> Int -> Int -> ST s Bool

* it does not check if the class method name is reserved name in frege or otherwise restricted. http://developer.android.com/reference/android/widget/RelativeLayout.html contains the value TRUE which was mapped to the following.

         pure native true android.widget.RelativeLayout.TRUE :: Int

Additionally would it be possible to have a whitelist of allowable classes and exclude generating code which references classes not in the list?

**Comment by mmhelloworld** [comment]
This issue is now partially fixed.

1. Constructors for abstract classes are now not generated
2. Frege keywords are now handled. If a Java class member results in a Frege keyword, it is now prefixed with `j` and suffixed with `'`

The only outstanding issue is to handle collision between static and instance methods (item# 2 in the original issue description).
